<?xml version="1.0" encoding="utf-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="agbot_car">

    <!-- Include Gazebo Parameters -->
    <xacro:include filename="$(find car_description)/urdf/car_gazebo.xacro" /> 

    <!-- Include ros2_control Plugins -->
    <xacro:include filename="$(find car_description)/urdf/car_ros2_control.xacro" />

    <!-- Include ros2_control Plugins -->
    <xacro:include filename="$(find car_description)/urdf/car_common_properties.xacro" />    

    <!-- Useful XACRO Variables (Properties) -->
    <xacro:property name="Pi" value="3.141592653589793238464" />
    <xacro:property name="effort" value="30.0" />
    <xacro:property name="velocity" value="10.0" />
    <xacro:property name="scale" value="0.0025 0.0025 0.0025"/>
    <xacro:property name="wheel_scale" value="0.002 0.002 0.002"/>
    <xacro:property name="camera_scale" value="0.002 0.002 0.002"/>     

    <xacro:property name="base_length" value="0.45" />
    <xacro:property name="base_width" value="0.225" />
    <xacro:property name="base_height" value="0.15" /> 
    <xacro:property name="wheel_radius" value="0.034" />
    <xacro:property name="wheel_width" value="0.05" />
    <xacro:property name="mast_length" value="0.05" />
    <xacro:property name="mast_width" value="0.05" />
    <xacro:property name="mast_height" value="0.1" />
    <xacro:property name="caster_radius" value="0.034" />


    <xacro:property name = "laser_radius" value = "0.025" />
    <xacro:property name = "laser_length" value = "0.10" />      
 
    <xacro:property name = "axel_radius" value = "0.007" />
    <xacro:property name = "axel_length" value = "0.308" /> 

    <!-- Useful Macros -->
    <xacro:macro name="default_inertia" params="mass">
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${mass}" />
            <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                     iyy="1.0" iyz="0.0"
                     izz="1.0" />
        </inertial>
    </xacro:macro>

    <xacro:macro name="default_transmission" params="name">
        <transmission name="transmission_${name}">
            <!-- <plugin>transmission_interface/DifferentialTransmission</plugin> -->
            <plugin>transmission_interface/SimpleTransmission</plugin>
            <actuator name="motor_${name}" role="actuator1"/>
            <joint name="${name}" role="joint1">
                <mechanical_reduction>1.0</mechanical_reduction>
            </joint>
        </transmission>
    </xacro:macro>         

    <!-- Robot Body -->
    <link name = "base_footprint">
    </link>

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
            <material name="maroon"/>
        </visual>
        <collision>
            <geometry>
                <box size="${base_length*1.1} ${base_width*1.1} ${base_height*1.1}"/>
            </geometry>
            <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>           
        </collision>
        <xacro:box_inertia m="18.0" l="${base_length}" w="${base_width}" h="${base_height}"
                           xyz = "0 0 ${base_height/2}" rpy="0 0 0" />
    </link>   

    <link name = "caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius = "${caster_radius}" />
            </geometry>
            <origin xyx = "${base_length / 3} 0 ${caster_radius}" rpy = "0 0 0" />
            <material name = "yellow" />            
        </visual>
        <collision>
            <geometry>
                <sphere radius = "${caster_radius}" />
            </geometry>
            <origin xyx = "${base_length / 3} 0 ${caster_radius}" rpy = "0 0 0" />
        </collision>
        <xacro:sphere_inertia m = "0.2" r = "${caster_radius}"
                              xyz = "${base_length / 3} 0 0" rpy = "0 0 0" />
    </link> 

    <link name="left_rear_wheel_link" >
        <visual>
            <geometry>
                <mesh filename="file://$(find agbot_full_description)/meshes/left_tire.stl" scale="${wheel_scale}"/>
            </geometry>
            <origin xyz = "0 0 0" rpy = "0 0 0" />
            <material name = "black" />
        </visual>
        <collision>
                <geometry>
                    <mesh filename="file://$(find agbot_full_description)/meshes/left_tire.stl" scale="${wheel_scale}"/>
            </geometry>
            <origin xyz = "0 0 0" rpy = "0 0 0" />           
        </collision>
        <xacro:wheel_inertia m="1.0" r = "${wheel_radius}" h = "${wheel_width}"
                             xyz = "0 0 0" rpy = "${Pi/2.0} -${Pi/2.0} 0" />
    </link>   

    <link name="right_rear_wheel_link" >
        <visual>
            <geometry>
                <mesh filename="file://$(find agbot_full_description)/meshes/right_tire.stl" scale="${wheel_scale}"/>
            </geometry>
            <origin xyz = "0 0 0" rpy = "0 0 0" />
            <material name = "black" />
        </visual>
        <collision>
            <geometry>
                <mesh filename="file://$(find agbot_full_description)/meshes/right_tire.stl" scale="${wheel_scale}"/>
            </geometry>
            <origin xyz = "0 0 0" rpy = "0 0 0" />           
        </collision>
        <xacro:wheel_inertia m="1.0" r = "${wheel_radius}" h = "${wheel_width}"
                             xyz = "0 0 0" rpy = "${Pi/2.0} -${Pi/2.0} 0" />
    </link>             

    <link name="rgb_camera_optical_link" >
    </link> 

    <link name="rgb_camera_link">
        <xacro:default_inertia mass="0.001"/>
        <visual>
            <origin xyz="0 -0.035 0.035" rpy="0 ${Pi/2} 0"/>
            <geometry>
                <mesh filename="file://$(find agbot_full_description)/meshes/pi_camera.STL" scale="${scale}"/>
            </geometry>
            <material name="grey"/>
        </visual>
        <collision>
            <origin xyz="0.2 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="file://$(find agbot_full_description)/meshes/pi_camera.STL" scale="${scale}"/>
            </geometry> 
        </collision>
    </link>     

    <link name="mast_link">
        <visual>
            <origin xyz="0 0 ${mast_height/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${mast_length} ${mast_width} ${mast_height}"/>
            </geometry>            
            <material name="pink"/>
        </visual>
        <collision>
            <geometry>
                <box size="${mast_length} ${mast_width} ${mast_height}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>           
        </collision>
        <xacro:box_inertia m="0.005" l="${mast_length}" w="${mast_width}" h="${mast_height}"
                            xyz = "0 0 0" rpy="0 0 0" />
    </link>      
    
    <link name="laser_frame_link">       
    </link>    

    <link name="laser_link">
        <visual>
            <geometry>
                <cylinder length="${laser_length}" radius="${laser_radius}" />
            </geometry>
            <origin xyz = "0 0 0" rpy = "0 0 0" />
            <material name="red"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${laser_length}" radius="${laser_radius}" />
            </geometry>
            <origin xyz = "0 0 0" rpy = "0 0 0" />
        </collision>
        <xacro:cylinder_inertia m="0.1" r="${laser_radius}" h="${laser_length}"
                                 xyz="0 0 0" rpy="0 0 0"/>
    </link>    

    <!-- Joint Descriptions -->
    <joint name="base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>

    <joint name="base_caster_wheel_joint" type="fixed">
        <parent link="base_link" />
        <child link="caster_wheel_link" />
        <origin xyz="${base_length / 3.0} 0 0" rpy="0 0 0" />
    </joint>     

    <joint name="right_rear_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link = "right_rear_wheel_link"/>
        <origin xyz="-${base_length/3.0} ${(base_width+wheel_width)/2} 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <joint name="left_rear_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link = "left_rear_wheel_link"/>
        <origin xyz="-${base_length/3.0} -${(base_width+wheel_width)/2} 0" ryp = "0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>   

    <joint name="camera_optical_joint" type="fixed">
        <parent link="base_link"/>
        <child link="rgb_camera_optical_link"/>
        <origin xyz = "${base_length/2} 0 ${base_height-(base_height/10)}" rpy = "0 0 0" />
    </joint> 

    <joint name = "rgb_camera_joint" type = "fixed" >        
        <parent link = "rgb_camera_optical_link" />
        <child link = "rgb_camera_link" />
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>        
    
    <joint name = "base_mast_joint" type = "fixed">
        <parent link = "base_link" />
        <child link = "mast_link" />
        <origin xyz="${((base_length/2)- 0.05)} 0 ${base_height}" rpy="0 0 0"/>
    </joint>

    <joint name="laser_frame_joint" type="fixed">
        <parent link="mast_link"/>
        <child link="laser_frame_link"/>
        <origin xyz="0 0 ${mast_height}" rpy="0 0 0"/>
    </joint>   

    <joint name="laser_joint" type="fixed">
        <parent link="laser_frame_link"/>
        <child link="laser_link"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>

    </joint>    

    <xacro:default_transmission name="right_front_wheel_joint" />
    <xacro:default_transmission name="left_front_wheel_joint" />   
    <xacro:default_transmission name="right_rear_wheel_joint" />
    <xacro:default_transmission name="left_rear_wheel_joint" />     

</robot>